routes/web.php
<?php

use App\Http\Controllers\ChatController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::middleware('auth')->prefix('chat')->group(function () {
    Route::get('/', [ChatController::class, 'index'])->name('chat');
    Route::get('/messages/{user_id}', [ChatController::class, 'getMessages'])->name('get.message');
    Route::post('/send/message', [ChatController::class, 'sendMessage'])->name('send.message');
    Route::delete('/message/delete/{chat_id}', [ChatController::class, 'deleteMessage'])->name('delete.message');

});

require __DIR__.'/auth.php';

app/Models/Chat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Chat extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'from_user_id',
        'to_user_id',
        'message',
        'is_read',
    ];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ChatController.php
<?php

namespace App\Http\Controllers;

use App\Models\Chat;
use App\Repository\ChatInterface;
use App\Repository\UserInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;


class ChatController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */

    public $chat;
    public $user;

    public function __construct(ChatInterface $chat, UserInterface $user)
    {
        $this->chat = $chat;
        $this->user = $user;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = $this->user->getOtherUsers($request);
        return view('chat', compact('users'));
        //
    }


    /**
     * Send message to the specific user
     *
     * @param Request $request
     * @return void
     */
    public function sendMessage(Request $request)
    {
        $user = Auth::user();
        try {
            $validator = Validator::make($request->all(), [
                'to_user_id' => 'required|exists:users,id',
                'message' => 'required',
            ]);

            if ($validator->fails()) {
                $response = [
                    "status" => false,
                    "message" => $validator->errors()->first(),
                    "data" => [],
                ];
            } else {
                
                $request->request->add(['from_user_id' => $user->id]);
                $message = $this->chat->createOrUpdate($request);

                $response = [
                    "status" => true,
                    "message" => 'Message added successfully',
                    "data" => $message,
                ];
            }
        } catch (\Exception $e) {
            report($e);

            $response = [
                "status" => false,
                "message" => 'Error : ' . $e->getMessage(),
                "data" => [],
            ];
        }

        return response()->json($response);
    }

    /**
     * Remove the specified message from storage.
     *
     * @param Request $request
     * @param int $user_id
     * @return \Illuminate\Http\Response
     */
    public function deleteMessage(Request $request, $chat_id)
    {
        try{
            $this->chat->deleteMessage($chat_id);
            $response = [
                "status" => true,
                "message" => 'Message deleted successfully',
                "data" => [],
            ];
        } catch (\Exception $e) {
            report($e);

            $response = [
                "status" => false,
                "message" => 'Error : ' . $e->getMessage(),
                "data" => [],
            ];
        }

        return response()->json($response);
    }

    /**
     * Get messages of the specific user
     *
     * @param Request $request
     * @param int $user_id
     * @return void
     */
    public function getMessages(Request $request, $user_id)
    {
        $user = Auth::user();
        $toUser = $this->user->getUserById($user_id);
        $messages = $this->chat->getMessages($user_id);
        return view('include.ajax_chat', compact('messages', 'user', 'toUser'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/chat.blade.php
<x-app-layout>

    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Chat') }}
        </h2>
    </x-slot>

    <div class="py-12" id="app">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="main flex-1 flex flex-col">
                        <div class="flex-1 flex h-full">
                            <div class="sidebar border-solid border-r-2 border-gray-400 mr-6 max-w-6xl">
                                <input type="hidden" name="to_user_id" id="to_user_id" value="">
                                <div class="flex-1 h-full overflow-auto px-2">
                                    @forelse ($users as $user)
                                    <a href="javascript:void(0)" onclick="getMessages({{ $user->id }})">
                                        <div
                                            class="user-list entry cursor-pointer transform bg-white mb-4 rounded p-4 flex shadow-md items-center">
                                            <div class="flex-2">
                                                <div class="w-12 h-12 relative">
                                                    <img class="w-12 h-12 rounded-full mx-auto"
                                                        src="{{ asset('frontend/images/user_avatar.png') }}"
                                                        alt="chat-user" />
                                                </div>
                                            </div>
                                            <div class="flex-1 px-2">
                                                <div class="w-48">
                                                    <span class="text-gray-800">{{ $user->name }}</span>
                                                    <span class="text-indigo-700">{{ $user->email }}</span>
                                                </div>
                                            </div>
                                        </div>

                                    </a>
                                        
                                    @empty
                                        <div>There are no registered users!</div>
                                    @endforelse 
                                </div>
                            </div>
                            <div class="chat-area flex-1 flex flex-col">
                                <div class="chat-area flex-1 flex flex-col hidden" id="right_panle">

                                    <div id="chat_container">

                                    </div>
                                    <div class="flex-2 pt-4 ">
                                        <form action="" method="post">
                                            @csrf
                                            <div class="write bg-white shadow flex rounded-lg">

                                                <div class="flex-1">
                                                    <textarea id="message" name="message" class="w-full block outline-none py-4 px-4 bg-transparent message-content"
                                                        rows="1" placeholder="Type a message..." autofocus></textarea>
                                                </div>
                                                <div class="flex-2 w-25 p-2 flex content-center items-center">
                                                    <div class="flex-1">
                                                        <button type="button"
                                                            class="bg-blue-400 w-10 h-10 rounded-full inline-block send-messsage"
                                                            onclick="sendMsg()">
                                                            <span class="inline-block align-text-bottom">
                                                                <svg fill="none" stroke="currentColor"
                                                                    stroke-linecap="round" stroke-linejoin="round"
                                                                    stroke-width="2" viewBox="0 0 24 24"
                                                                    class="w-6 h-6 text-white">
                                                                    <path d="M5 13l4 4L19 7"></path>
                                                                </svg>
                                                            </span>
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(".user-list").click(function() {
            $(".user-list").removeClass("active");
            $(this).addClass("active");
        });

        function getMessages(to_user_id) {
            $.ajax({
                type: "GET",
                data: {},
                headers: {
                    'X-CSRF-TOKEN': $("input[name='_token']").val()
                },
                url: base_url + "/chat/messages/" + to_user_id,
                success: function(data) {
                    $('#right_panle').show();
                    $('#to_user_id').val(to_user_id);
                    $('#chat_container').html(data);

                    document.getElementById("messages").scrollTop = document.getElementById("messages")
                        .scrollHeight;

                },
                error: function(data, e) {
                    console.log("Something went wrong. Please try again later.");
                }
            });
        }

        function sendMsg() {
            var to_user_id = $('#to_user_id').val();
            var message = $('#message').val();
            $.ajax({
                type: "POST",
                data: {
                    'to_user_id': to_user_id,
                    'message': message
                },
                headers: {
                    'X-CSRF-TOKEN': $("input[name='_token']").val()
                },
                url: base_url + "/chat/send/message",
                success: function(data) {
                    getMessages(to_user_id);
                    $('#message').val('');
                },
                error: function(data, e) {
                    console.log("Something went wrong. Please try again later.");
                }
            });
        }

        function deleteMsg(chat_id) {
            if (confirm('Are you sure to delete this message?')) {
                var to_user_id = $('#to_user_id').val();
                $.ajax({
                    type: "DELETE",
                    data: {},
                    headers: {
                        'X-CSRF-TOKEN': $("input[name='_token']").val()
                    },
                    url: base_url + "/chat/message/delete/" + chat_id,
                    success: function(data) {
                        getMessages(to_user_id);
                    },
                    error: function(data, e) {
                        console.log("Something went wrong. Please try again later.");
                    }
                });
            }


        }


        setInterval(() => {
            var to_user_id = $('#to_user_id').val();
            if (to_user_id) {
                getMessages(to_user_id);
            }
        }, 1000);
    </script>

</x-app-layout>

resources/views/dashboard.blade.php
<x-app-layout>


    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/include/ajax_chat.blade.php
    <div class="flex-3">
        <h2 class="text-xl py-1 mb-8 border-b-2 border-gray-200"><span>Chatting with
                <b>{{ $toUser->name }}</b></span></h2>
    </div>
    <div class="messages flex-1 overflow-auto" id="messages">
        @forelse ($messages as $message)
            <span>
                
                
                @php
                    $chat_time = date('M d, Y h:i A', strtotime(convertUtcDatetoLocal($message->created_at)))
                @endphp
                @if ($user->id == $message->from_user_id)
                    <div class="message me mb-4 flex text-right">
                        <div class="flex-1 px-2">
                            <div class="flex items-center justify-end">
                                <div class="inline-block bg-blue-600 rounded-full p-2 px-6 text-white">
                                    <span>{{ $message->message }}</span>
                                </div>
                                <a href="javascript:void(0)" onclick="deleteMsg({{$message->id}})">
                                    <img class="w-5" src="{{ asset('frontend/images/trash.png') }}"
                                        alt="delete-message" />
                                </a>

                            </div>
                            <div class="pr-4"><small class="text-gray-500">{{ $chat_time }}</small></div>
                        </div>
                    </div>
                    
                @else
                    <div class="message mb-4 flex">
                        <div class="flex-2">
                            <div class="w-12 h-12 relative">
                                <img class="w-12 h-12 rounded-full mx-auto"
                                src="{{ asset('frontend/images/user_avatar.png') }}"
                                    alt="chat-user" />
                            </div>
                        </div>
                        <div class="flex-1 px-2">
                            <div class="inline-block bg-gray-300 rounded-full p-2 px-6 text-gray-700">
                                <span>{{ $message->message }}</span>
                            </div>
                            <div class="pl-4"><small class="text-gray-500">{{ $chat_time }}</small></div>
                        </div>
                    </div>


                   
                @endif


            </span>
        @empty
            <div>There is no message!</div>
        @endforelse

    </div>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        
        <!-- Scripts -->
        <script
        src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
        <script src="{{ asset('js/app.js') }}" defer></script>
        <script src="https://momentjs.com/downloads/moment.min.js"></script>
        <script src="https://momentjs.com/downloads/moment-timezone-with-data-10-year-range.min.js"></script>
        
        <script>
            var base_url = '{{ url('/') }}';
            document.cookie = "myTimeZone = "+moment.tz.guess();
        </script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>

                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('chat')" :active="request()->routeIs('chat')">
                        {{ __('Chat') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>